builders:
  config_builder:
    import: "package:config_builder/config_builder.dart"
    builder_factories:
      - "configBuilder"
    build_extensions: {".config.json": [".dart"]}
    auto_apply: root_package
    build_to: cache
