builders:
  json_config_builder:
    import: "package:json_config_builder/json_config_builder.dart"
    builder_factories:
      - "jsonConfigBuilder"
    build_extensions: {".json": [".dart"]}
    auto_apply: root_package
