name: json_config_builder
description: A builder to create a configuration dart file from a json spec
homepage: https://github.com/52inc/config_builder
repository: https://github.com/52inc/config_builder
issue_tracker: https://github.com/52inc/config_builder/issues
version: 0.0.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  build: ^1.2.2
  build_config: ">=0.4.1 <0.4.2"
  dart_style: ^1.3.4

dev_dependencies:
  test: 1.14.2
  indent: ^1.0.0+2
